name = "whynotsleep-channel-router"
main = "channel-router.js"
compatibility_date = "2026-05-07"

routes = [
  { pattern = "blog.whynotsleep.cc/*", zone_name = "whynotsleep.cc" },
  { pattern = "game.whynotsleep.cc/*", zone_name = "whynotsleep.cc" },
  { pattern = "project.whynotsleep.cc/*", zone_name = "whynotsleep.cc" },
  { pattern = "manuscript.whynotsleep.cc/*", zone_name = "whynotsleep.cc" },
  { pattern = "design.whynotsleep.cc/*", zone_name = "whynotsleep.cc" },
  { pattern = "note.whynotsleep.cc/*", zone_name = "whynotsleep.cc" },
  { pattern = "life.whynotsleep.cc/*", zone_name = "whynotsleep.cc" },
]
